### ISSUE TITLE
Is it ready for production usage?

### ISSUE THREAD

**Issue by gustawdaniel** [nodefony/nodefony-starter#62]
Can you describe status of this project?

Are you open for contributors?
Have this project official sponsor?

One of strongest advantages of Symfony is great documentation. I see that docs

https://nodefony.net/documentation/5.0.9/nodefony

is incomplete now. For example link to `mail` does not works. 

How can you describe plans of development of documentation?

**Comment by ccamensuli** [comment]
hello daniel,

This project is ready for production and open for contributions in  [nodefony-core](https://github.com/nodefony/nodefony-core) repository.

The documentation is in progress but I'm running out of time .

For now the users who use it, are trained by me, and I hope to produce more documentation in the coming months

 A release 5.2 is planned for January with a better integration of Progressive JavaScript Framework vue.js

A reformatted users-bundle to respond the needs of secure APIs .

I will try to feed the documentation during this period.
I know that a project without a serious documentation discourages users but I have to make choices for the moment.

if you have any questions I remain at your disposal .

christophe
